/**
 * Keys used when defining object metadata with reflect-metadata.
 */
export enum MetadataKeys {
  CONTROLLER_PATH = "CONTROLLER_PATH",
  CONTROLLER_ROUTES = "CONTROLLER_ROUTES",
  MIDDLEWARE_LIST = "MIDDLEWARE_LIST",
  DEPENDENCY_KEY = "DEPENDENCY_KEY",
  DEPENDENCY_CONFIG = "DEPENDENCY_CONFIG",
  MIDDLEWARE_CONFIG = "MIDDLEWARE_CONFIG",
}
