/**
 * Keys used when defining object metadata with reflect-metadata.
 */
export enum MetadataKeys {
  CONTROLLER_PATH = "CONTROLLER_PATH",
  CONTROLLER_ROUTES = "CONTROLLER_ROUTES",
  MIDDLEWARE_LIST = "MIDDLEWARE_LIST",
  DEPENDENCY_KEY = "DEPENDENCY_KEY",
  DEPENDENCY_CONFIG = "DEPENDENCY_CONFIG",
  MIDDLEWARE_CONFIG = "MIDDLEWARE_CONFIG",
  WEB_SOCKET_NAMESPACE = "WEB_SOCKET_NAMESPACE",
  WEB_SOCKET_CONNECTION_HANDLER = "WEB_SOCKET_CONNECTION_HANDLER",
  WEB_SOCKET_EVENT_HANDLERS = "WEB_SOCKET_EVENT_HANDLERS",
}
